version: "2.4"
services:
    fluent-bit:
        image: fluent-bit
        build:
          context: .
        command:
          - /fluent-bit/bin/fluent-bit
          - --config=/etc/fluent-bit/fluent-bit.conf
        env_file:
          - .env
        ports:
          - 24224:24224
        logging:
          driver: fluentd
          options:
            tag: efk.fluent-bit